### ISSUE TITLE
move application config to YAML file

### ISSUE THREAD

**Issue by yukron** [RChehowski/LunchChooser#4]
Places seem to be hardcoded, please consider moving configuration into YAML file.

**Comment by RChehowski** [comment]
We never forget who we're working for

**Comment by RChehowski** [comment]
Hi @yukron ! I am very glad to notify you that after just a few meetings with our board of directors, we decided to dedicate 1.500.000$ to implement this feature. After long negotiations with Boston Dynamics and Lockheed Martin, we used the ones of the most modern security algorithms from the NSA (we even hired a nefarious security expert dispersing our employees, drinking (not) coffee at work with his ebony Colt 1911) to bring stability and security to your user experience. So now you can enjoy using YML in our cutting edge solution. No pasaran.
